# Generated by Django 6.0.5 on 2026-06-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dailytask_leaveapplication_salaryrecord_sessionnote_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="email",
            field=models.EmailField(default="noemail@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="name",
            field=models.CharField(default="noemail@gmail.com", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="phone",
            field=models.CharField(default="Admin", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
