# Generated by Django 6.0.5 on 2026-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_appointment_email_appointment_name_appointment_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("seen", "Seen"),
                ],
                default="sent",
                max_length=10,
            ),
        ),
    ]
