# Generated by Django 6.0.5 on 2026-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_message_options_remove_message_is_read_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="status",
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
