# Generated by Django 6.0.5 on 2026-06-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_message_options_alter_message_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
    ]
