# Generated by Django 6.0.6 on 2026-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_name", models.CharField(max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="clinic_logo/"),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                (
                    "appointment_fee",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                (
                    "followup_fee",
                    models.DecimalField(decimal_places=2, default=300, max_digits=10),
                ),
                ("session_duration", models.IntegerField(default=45)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("enable_chat", models.BooleanField(default=True)),
                ("enable_payments", models.BooleanField(default=False)),
                ("enable_otp_reset", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
