# Generated by Django 6.0.6 on 2026-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_clinicsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("meta_description", models.TextField()),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
