# Generated by Django 6.0.6 on 2026-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_blog_updated_at_alter_blog_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/"),
        ),
    ]
