# Generated by Django 6.0.6 on 2026-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_hospital_subscriptionplan_profile_is_platform_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consultation / treatment fee in ₹', max_digits=8, null=True),
        ),
    ]
