# Generated by Django 6.0.6 on 2026-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_hospital_razorpay_paymentrecord_razorpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='evening_clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='evening_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='morning_clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='morning_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 PM'), ('11:30', '11:30 PM'), ('12:00', '12:00 PM'), ('12:30', '12:30 PM'), ('04:00', '04:00 PM'), ('04:30', '04:30 PM'), ('05:00', '05:00 PM'), ('05:30', '05:30 PM'), ('06:00', '06:00 PM'), ('06:30', '06:30 PM'), ('07:00', '07:00 PM'), ('07:30', '07:30 PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
