# Generated by Django 6.0.6 on 2026-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="blogs/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
    ]
