# Generated by Django 6.0.6 on 2026-06-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_blog_meta_description_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
