# Generated by Django 6.0.6 on 2026-06-18 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/before_after/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/before_after/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Orthopaedic', 'Orthopaedic'), ('Neurological', 'Neurological'), ('Sports', 'Sports Rehab'), ('Pediatric', 'Pediatric'), ('Posture', 'Posture & Spine'), ('Recovery', 'Patient Recovery')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown on listing page'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_title', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('added_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
