// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/services-page/CardGrid.tsx": () => import("../components/mockups/services-page/CardGrid.tsx"),
  "./components/mockups/services-page/CleanMinimal.tsx": () => import("../components/mockups/services-page/CleanMinimal.tsx"),
  "./components/mockups/services-page/ModernDark.tsx": () => import("../components/mockups/services-page/ModernDark.tsx")
};
